services:
  postgres:
    image: postgres:latest
    container_name: Witcher
    ports:
      - "5433:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: witcherboard
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: