spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5433/witcherboard
    username: postgres
    password: 123

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  data:
    mongodb:
      uri: mongodb://mongo:123@localhost:27017/witcherboard?authSource=admin

jwt:
  secret: devdevdevdevdevdevdevdevdevdevdevdevdevdevdevdevdevdevdevdevdevdevdevdevdevdevdevdevdevdev
