spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5433/witcherboard
    username: postgres
    password: 123

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  data:
    mongodb:
      host: localhost
      port: 27017
      database: witcherboard
      username: mongo
      password: 123

jwt:
  secret: devdevdevdevdevdevdevdevdevdevdevdevdevdevdevdevdevdevdevdevdevdevdevdevdevdevdevdevdevdev
