spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5433/witcherboard
    username: postgres
    password: 123

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

jwt:
  secret: devdevdevdevdevdevdevdevdevdevdevdevdevdevdev
